### PR TITLE
Few enhancements to ucarp

### PR DESCRIPTION
**Pull request by miconda**
Hello, I added few new features to ucarp, starting from the master branch in your repo. In summary, they are:
1) option to encapsulate advertisement packet in UDP payload and send to the other peer in a group of two servers (the master and the backup). The reason for it was that in some virtualized systems (e.g., vmware), it is sometime hard to get multicast/broadcast working, specially if the environment was preconfigured without such support and one doesn't have admin rights to change in the management interface of the virtual machines. It is working only in a pair of two servers, but could be extended in the future. The advertisement packet is completely embedded in UDP, then extracted and passed to the packethandler() function, so any change in the format of the advertisement should be transparent. Also, the patch got pretty non-intrusive to the existing code
2) option to set a threshold for debug messages -- it is sometime handy for troubleshooting to compile using --with-debug and control the verbosity from the command line parameter
3) option to write PID in a file -- useful for monitoring -- while some OS-es have their init.d set of functions able to do this, there are situations when simply having this feature make things a lot easier
4) option to write details of the current state in a file -- again useful for monitoring tools. I have seen another fork in github with a commit trying to achieve the same thing. The difference is that this patch updates the content of the state file in the spawned process for executing UP/DOWN scripts, thus not affecting (like potentially blocking) main process
5) added .gitignore file -- no really relevant, but is good to get proper statuses of git local copy and not add by mistake some binaries or tmp files in the repo

Hope you will find some of these features interesting enough to merge them in the main project. Thanks, Daniel

### CODE REVIEW

**Comment by mterron** [comment]
Is this patchiest likely to be merged? It's been sitting here for 3 years. I think it is a very useful feature.

**Comment by petiepooo** [comment]
Hey, @miconda.  Thanks for this pull request.
@jedisct1 has been too busy to give this legacy project much attention, so he recently granted me commit privileges on this repo. In the next few weeks, I plan to pull in some new features and come up with a new point release to push downstream.
I like the work you've done, and will likely be cherry-picking some of the patches in this PR for inclusion.  Since this PR is stale, however, I'll just close it for now.  I have copied your repo to preserve your patches.  Thanks!

**Comment by miconda** [comment]
Hello, glad to hear someone is picking up on this project!

In case you need clarifications about parts of the patches, let me know. I would be happy to see as much as possible merged, or those features added via a different implementation.

I am still using my branch in production, because I need the option to send advertisement encapsulated in UDP unicast  (commit 814c0d5). It runs without issues from the moment I did the PR here.

Having the state in a file is also useful for me, because I can check it easily with monitoring tools.

**Comment by petiepooo** [comment]
@miconda, Thanks.  I'm happy to hear the UDP feature is working well for you.  I haven't tested it after rebasing your patches in my fork, but will want to do that before I roll them upstream to here.

I'm questioning the utility of the state-file patch.  Right now the interface and virtual IP are sent as arguments to the up/down scripts.  If that's all that's needed in a state file, the scripts could easily be modified to write a file as it brings the VIP up or down.

If ucarp passed more arguments (or environment variables) to the up/down scripts (eg local IP, VID, internal state), would that be sufficient to create your statefile?  That's useful in other ways, as it could allow a single script to perform either the up or down action depending on how its called.

I'm trying to find a balance between usefulness, compatibility, and feature bloat, and I think a status file might be best left to shell scripting rather than C...  There's already a bewildering number of arguments, to the point where most authors would turn to reading them from a config file.

**Comment by miconda** [comment]
The reason for having the state file controlled by ucarp was the fact that it is something about ucarp internals and this is a reliable way to do it. I did have it as something written by up/down scripts, but I encountered some situations when the scripts were not run mainly due to human errors (typos, etc.). Having the state file as something reliable made the monitoring easier and detection of issues faster. I still write the switch of state in a log file from up/down scripts in a log file for purpose of tracking the history of the events.

It is not a big patch and quite non intrusive, if it is not enabled via command line parameter, the impact is very minimal.

**Pull request closed without merging**
